export AZR_EMAIL_CONNECTION_STRING=xxxxxxx
export AZR_EMAIL_SENDER_ADDRESS=xxxxx

echo 'AZR_EMAIL_CONNECTION_STRING: '$AZR_EMAIL_CONNECTION_STRING
echo 'AZR_EMAIL_SENDER_ADDRESS: '$AZR_EMAIL_SENDER_ADDRESS
